caldera_criticalmass_live_frontpage:
    path:     /
    defaults: { _controller: CalderaCriticalmassLiveBundle:Default:index }

caldera_criticalmass_live_live_city:
    path:     /{citySlug}
    defaults: { _controller: CalderaCriticalmassLiveBundle:Live:city }
    options:
        expose: true

caldera_criticalmass_live_content:
    path:     /content/{contentSlug}
    defaults: { _controller: CalderaCriticalmassLiveBundle:Content:show }
