caldera_criticalmass_live_frontpage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

caldera_criticalmass_live_live_city:
    path:     /{citySlug}
    defaults: { _controller: AppBundle:Live:city }
    options:
        expose: true

caldera_criticalmass_live_api_foo:
    path:     /api/getpositions
    defaults: { _controller: AppBundle:Api:getPositions }
    methods: ['GET']