caldera_criticalmass_live_frontpage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

caldera_criticalmass_live_live_city:
    path:     /{citySlug}
    defaults: { _controller: AppBundle:Live:city }
    options:
        expose: true

caldera_criticalmass_live_api_position:
    path:     /api/positions
    defaults: { _controller: AppBundle:Api:getPositions }
    methods: ['GET']
    options:
        expose: true

caldera_criticalmass_live_api_ride:
    path:     /api/rides
    defaults: { _controller: AppBundle:Api:getRides }
    methods: ['GET']
    options:
        expose: true

caldera_criticalmass_live_content:
    path:     /content/{slug}
    defaults: { _controller: AppBundle:Static:display }

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: AppBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]
