parameters:
#    caldera_criticalmass_live.example.class: Caldera\Bundle\CriticalmassLiveBundle\Example

services:
    criticalmass.manager.incident_manager:
        class: AppBundle\Manager\PositionManager
        arguments: ['@doctrine', '@fos_elastica.manager']
